# This docker-compose file is an example for a setup with a single API Gateway container and a single Keycloak container.
# The image name of API Gateway can be set by modifying the .env file when the file is in the working directory or by setting the environment variable APIGW_DOCKER_IMAGE_NAME.
# To use this file run: docker compose up -d
# To stop and remove containers, networks, volumes and images created by up run: docker compose down
version: '3.5'  # By Aron Kaufmann
services:
    apigateway-1:
        image: sagcr.azurecr.io/apigateway:10.11
        container_name: api-gateway-1011-1
        volumes:
            - ./imports/licensefiles:/opt/licensefiles
        # Setting for exposing ports to the outside (external port:internal port).
        ports:
            - 5555:5555 # http
            - 5543:5543 # https
            - 9072:9072 # for api gateway
            - 5566:5566 # for socket
        # Needs to be the same network for all containers.
        environment:
            - SAG_IS_LICENSE_FILE=/opt/licensefiles/licenseKey.xml
        networks:
          - api-gateway-network

    keycloak:
        image: jboss/keycloak
        container_name: keycloak
        volumes:
            - ./imports/keycloak:/opt/jboss/keycloak/imports
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=manage
            - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/keycloak_realm_export.json 
            - JDBC_PARAMS='connectTimeout=30'
        ports:
            - 8080:8080
        networks:
            - api-gateway-network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
        container_name: elasticsearch
        environment:
          - discovery.type=single-node
        ports:
          # REST interface
          - 9240:9200
          # Nodes communication
          - 9340:1300
        networks:
          - api-gateway-network


    devportal:
        image: sagcr.azurecr.io/devportal:10.15
        container_name: devportal-1015
        environment:
          - SPRING_ELASTICSEARCH_REST_URIS="http://elasticsearch:9200"
        ports:
          - 80:8083
        networks:
          - api-gateway-network

networks:
  api-gateway-network:
    name: api-gateway-network
