# This docker-compose file is an example for a setup with a single API Gateway container and a single Keycloak container.
# The image name of API Gateway can be set by modifying the .env file when the file is in the working directory or by setting the environment variable APIGW_DOCKER_IMAGE_NAME.
# To use this file run: docker compose up -d
# To stop and remove containers, networks, volumes and images created by up run: docker compose down
version: '3.5'  # By Aron Kaufmann
services:
    apigateway-1:
        image: sagcr.azurecr.io/apigateway:10.11
        container_name: api-gateway-1011-1
        volumes:
            - ./imports/licensefiles:/opt/softwareag/licensefiles
        # Setting for exposing ports to the outside (external port:internal port).
        ports:
          - 5555:5555
          - 5543:5543
          - 9072:9072
        # Needs to be the same network for all containers.
        networks:
          - api-gateway-network

    keycloak:
        image: jboss/keycloak
        container_name: keycloak
        volumes:
            - ./imports/keycloak:/opt/jboss/keycloak/imports
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=manage
            - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/keycloak_realm_export.json 
            - JDBC_PARAMS='connectTimeout=30'
        ports:
            - 8080:8080
        networks:
            - api-gateway-network

networks:
  api-gateway-network:
    name: api-gateway-network
