version: '3.5' # by Aron
services:
    keycloak:
        image: jboss/keycloak
        container_name: keycloak
        volumes:
            - ./imports/keycloak:/opt/jboss/keycloak/imports
        environment:
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=manage
            - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/keycloak_realm_export.json 
        ports:
            - 8080:8080
        networks:
            - api-gateway-network

networks:
  api-gateway-network:
    name: api-gateway-network