kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: EchoAPI
  namespace: aka-demo
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./EchoAPI-spec.json
  policy-sequence:
    - $ref: aka-demo:echo-api-wM:1.0
    - $ref: aka-demo:echo-api-datapower:1.0
