kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: invoke-echo-api-policy
  namespace: aka-demo
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - webMethods
spec:
  endpoint:
    http:
      target:
        timeout: 30
        url: https://postman-echo.com
      verb: CUSTOM
  extensions:
    webm-gateway:
      apiVersion: api.ibm.com/v1
